codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: false
      python:
        target: 85%
        threshold: 1%
        paths: "jpype/"
      cpp:
        target: 80%
        threshold: 1%
        paths: 
        - "native/common/"
        - "native/python/"
      java:
        target: 75%
        threshold: 2%
        paths: "native/java/"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
