# JPype CI pipeline
trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - .azure/build.yml
    - doc/*
    - setup.py
    - setupext/*
    - jpype/*
    - native/*
    - test/*

variables:
# indicate whether the testsuite should skip long running tests or not.
- name: jpypetest.fast
  value: 'false'

jobs:
- job: Deps
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/ivy.yml

- job: Documentation
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/documentation.yml

- job: Coverage
  pool:
    vmImage: "ubuntu-latest"
  dependsOn: Deps
  steps:
  - template: scripts/deps.yml
  - template: scripts/coverage.yml

- job: Tracing
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/tracing.yml

- job: Test
  dependsOn: Deps
  strategy:
    matrix:
      linux-3.7:
        imageName: "ubuntu-latest"
        python.version: '3.7'
      linux-3.8:
        imageName: "ubuntu-latest"
        python.version: '3.8'
      linux-3.9:
        imageName: "ubuntu-latest"
        python.version: '3.9'
      linux-3.10:
        imageName: "ubuntu-latest"
        python.version: '3.10'
      linux-3.11:
        imageName: "ubuntu-latest"
        python.version: '3.11'
      linux-3.12:
        imageName: "ubuntu-latest"
        python.version: '3.12'
      windows-3.7:
        imageName: "windows-2019"
        python.version: '3.7'
      windows-3.8:
        imageName: "windows-2019"
        python.version: '3.8'
      windows-3.9:
        imageName: "windows-2019"
        python.version: '3.9'
        #jpypetest.fast: 'true'
      windows-3.10:
        imageName: "windows-2019"
        python.version: '3.10'
      windows-3.11:
        imageName: "windows-2019"
        python.version: '3.11'
      windows-3.12:
        imageName: "windows-2019"
        python.version: '3.12'
      mac-3.9:
        imageName: "macos-11"
        python.version: '3.9'
        jpypetest.fast: 'true'

  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/deps.yml
  - template: scripts/test.yml

- job: Debug
  condition: eq(1,0)
  dependsOn: Deps
  strategy:
    matrix:
      linux-3.8:
        imageName: "ubuntu-16.04"
        jdk_version: "1.11"
        python.version: '3.8'
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/deps.yml
  - template: scripts/debug.yml

