# JPype CI pipeline
trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - .azure/build.yml
    - doc/*
    - setup.py
    - setupext/*
    - jpype/*
    - native/*
    - test/*

variables:
# indicate whether the testsuite should skip long-running tests or not.
- name: jpypetest.fast
  value: 'false'
- name: system.debug
  value: 'true'

jobs:
- job: Deps
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/ivy.yml

- job: Documentation
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/documentation.yml

- job: Coverage
  pool:
    vmImage: "ubuntu-latest"
  dependsOn: Deps
  steps:
  - template: scripts/deps.yml
  - template: scripts/coverage.yml

- job: Tracing
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/tracing.yml

- job: Test
  dependsOn: Deps
  strategy:
    matrix:
      # Linux
      linux_py38_jdk8:  # todo: 3.8 will be EOL on October 31, 2024
        imageName: "ubuntu-latest"
        python.version: '3.8'
        jdk.version: '8'
      linux_py39_jdk11:
        imageName: "ubuntu-latest"
        python.version: '3.9'
        jdk.version: '11'
      linux_py310_jdk17:
        imageName: "ubuntu-latest"
        python.version: '3.10'
        jdk.version: '17'
      linux_py311_jdk17:
        imageName: "ubuntu-latest"
        python.version: '3.11'
        jdk.version: '17'
      linux_py312_jdk17:
        imageName: "ubuntu-latest"
        python.version: '3.12'
        jdk.version: '17'
      linux_py313_jdk17:
        imageName: "ubuntu-latest"
        python.version: "3.13"
        jdk.version: '17' # jdk 22 is not there yet.
      #linux_py314_jdk22:
      #  imageName: "ubuntu-latest"
      #  python.version: "3.14.0-alpha.0"
      #  jdk.version: '22'
      # Windows
      windows_py38_jdk8:
        imageName: "windows-2019"
        python.version: '3.8' # todo: 3.8 will be EOL on October 31, 2024
        jdk.version: '8'
      windows_py39_jdk11:
        imageName: "windows-2019"
        python.version: '3.9'
        jdk.version: '11'
      windows_py310_jdk8:
        imageName: "windows-2019"
        python.version: '3.10'
        jdk.version: '8'
      windows_py311_jdk17:
        imageName: "windows-2019"
        python.version: '3.11'
        jdk.version: '17'
      windows_py312_jdk21:
        imageName: "windows-2019"
        python.version: '3.12'
        jdk.version: '21'
      # OSX, we only test an old Python version with JDK8 and recent Py with recent JDK.
      mac_py38_jdk8:
        imageName: "macos-13"
        python.version: '3.8' # todo: 3.8 will be EOL on October 31, 2024
        jpypetest.fast: 'true'
        jdk.version: '8'
      mac_py312_jdk17:
        imageName: "macos-13"
        python.version: '3.12'
        jpypetest.fast: 'true'
        jdk.version: '17'

  pool:
    vmImage: $(imageName)
  steps:

  - template: scripts/deps.yml
  - template: scripts/test.yml

- job: Debug
  condition: eq(1,0)
  dependsOn: Deps
  strategy:
    matrix:
      linux_py38_jdk11:
        imageName: "ubuntu-16.04"
        jdk.version: "11"
        python.version: '3.8'
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/deps.yml
  - template: scripts/debug.yml
