# JPype Release pipeline
trigger: none
pr:
  branches:
    include:
    -  releases/*
  paths:
    include:
    - .bumpversion.cfg
    - .azure/release.yml

variables:
  package_name: jpype1

stages:
- stage: Initial
  jobs:
  - job: SourceDistribution
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - template: scripts/sdist.yml
      parameters:
        artifact: true
    - template: scripts/ivy.yml

- stage: Package
  jobs:
  # From https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/
  - job: ManyLinux
    condition: eq(1,1)
    timeoutInMinutes: 360
    strategy:
      matrix:
        aarch64:
          arch: aarch64
          plat: manylinux2014_aarch64
          image: quay.io/pypa/manylinux2014_aarch64
          python.architecture: aarch64
        #arm64Bit:
        #  arch: armv71
        #  plat: musllinux_1_2
        #  image: quay.io/pypa/musllinux_1_2_armv7l
        #  python.architecture: armv71
        x86_64:
          arch: x86_64
          plat: manylinux2014_x86_64
          image: quay.io/pypa/manylinux2014_x86_64
#          plat: musllinux_1_2
#          image: quay.io/pypa/musllinux_1_2_x86_64
          python.architecture: x64
        i686:
          arch: i686
          plat: manylinux2014_i686
          image: quay.io/pypa/manylinux2014_i686
#          plat: musllinux_1_2
#          image: quay.io/pypa/musllinux_1_2_i686
          python.architecture: x86
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - template: scripts/deps.yml
    - template: scripts/wheels-linux.yml
    - template: scripts/publish-dist.yml

  - job: Windows_x64
    condition: eq(1,1)
    strategy:
      matrix:
        Python39:
          python.version: '3.9'
          python.architecture: 'x64'
        Python310:
          python.version: '3.10'
          python.architecture: 'x64'
        Python311:
          python.version: '3.11'
          python.architecture: 'x64'
        Python312:
          python.version: '3.12'
          python.architecture: 'x64'
        Python313:
          python.version: '3.13'
          python.architecture: 'x64'
    pool:
      vmImage: "windows-2022"
    steps:
    - template: scripts/deps.yml
    - template: scripts/python.yml
      parameters:
        version: '$(python.version)'
        architecture: '$(python.architecture)'
    - template: scripts/jdk.yml
      parameters:
        version: '11'
    - template: scripts/wheels.yml
    - template: scripts/publish-dist.yml

  - job: OSX
    condition: eq(1,1)
    variables:
      python.architecture: 'x64'
    strategy:
      matrix:
        Python39:
          python.version: '3.9'
        Python310:
          python.version: '3.10'
        Python311:
          python.version: '3.11'
        Python312:
          python.version: '3.12'
        Python313:
          python.version: '3.13'
    pool:
      vmImage: "macos-13"
    steps:
    - template: scripts/deps.yml
    - script: .azure/scripts/osx-python.sh '$(python.version)'
      displayName: Install Python.org Python
    - template: scripts/jdk.yml
      parameters:
        version: '11'
    - template: scripts/wheels.yml
    - template: scripts/publish-dist.yml
