# JPype Release pipeline
trigger: none
pr: 
  branches:
    include:
    -  releases/*
  paths:
    include:
    - .bumpversion.cfg
    - .azure/release.yml

variables:
  package_name: JPype1

stages:
- stage: Initial
  jobs:
  - job: SourceDistribution
    pool: 
      vmImage: "ubuntu-16.04"
    steps:
    - template: scripts/sdist.yml
    - template: scripts/ivy.yml

- stage: Package
  jobs:
  # From https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/
  - job: ManyLinux
    condition: eq(1,1)
    strategy:
      matrix:
        64Bit2010:
          arch: x86_64
          plat: manylinux2010_x86_64
          image: quay.io/pypa/manylinux2010_x86_64
          python.architecture: x64
        64Bit2014:
          arch: aarch64
          plat: manylinux2014_aarch64
          image: quay.io/pypa/manylinux2014_aarch64
          python.architecture: aarch64
        64Bit:
          arch: x86_64
          plat: manylinux1_x86_64
          image: quay.io/pypa/manylinux1_x86_64
          python.architecture: x64
        32Bit:
          arch: i686
          plat: manylinux1_i686
          image: quay.io/pypa/manylinux1_i686
          python.architecture: x86
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - template: scripts/deps.yml
    - template: scripts/wheels-linux.yml
    - template: scripts/publish-dist.yml

  - job: Windows_x64
    condition: eq(1,1)
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
          python.architecture: 'x64'
        Python37:
          python.version: '3.7'
          python.architecture: 'x64'
        Python38:
          python.version: '3.8'
          python.architecture: 'x64'
          #Python39:
          #python.version: '3.9'
          #python.architecture: 'x64'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - template: scripts/deps.yml
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: '$(python.architecture)'
    - template: scripts/jdk.yml
      parameters:
        version: '8'
    - template: scripts/wheels.yml
    - template: scripts/publish-dist.yml

  - job: OSX
    condition: eq(1,1)
    variables:
      python.architecture: 'x64'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    pool:
      vmImage: "macOS-10.14"
    steps:
    - template: scripts/deps.yml
    - script: .azure/scripts/osx-python.sh '$(python.version)'
      displayName: Install Python.org Python
    - template: scripts/jdk.yml
      parameters:
        version: '8'
    - template: scripts/wheels.yml
    - template: scripts/publish-dist.yml
