numpy_cfg:
  - 'disable'
  # TODO: selectors do not work for variants?
  - 1.8  # [not (win and (py35 or py36))]
  #  - 1.11  # [win and py36]

python:
  - 2.7
  - 3.6

java:
  - '>=7.0,<8'
  - '>=8.0,<9'

