package:
  name: jpype
  version: dev

source:
  path: ../../

build:
  number: 0
  string: np_{{ numpy }}_jdk_{{ java[2] }}_py{{ python }}
  script:
    # on linux/osx we use build.sh
    - python setup.py install --single-version-externally-managed --record record.txt  # [win] 

requirements:
  build:
    - python
    - setuptools
    - ccache-toolchain  # [osx or linux] 
    {% if numpy_cfg != 'disable' %} 
    - numpy {{ numpy }}
    {% endif %}

  run:
    - python
    {% if numpy_cfg != 'disable' %} 
    - numpy
    {% endif %}

test:
  source_files:
    - test/
  requires:
    - ant
    - openjdk {{ java }}
    - pytest-faulthandler
    - pytest-xdist
    - mock
    - unittest2  # [py2k]
  imports:
    - jpype
  commands:
    - cd test; ant
    - cd jpypetest; pytest *.py -v --boxed

about:
  home: https://github.com/originell/jpype/
  license: Apache
  license_file: LICENSE
  summary: 'A Python to Java bridge.'
  description: 'A Python to Java bridge.'
  doc_url: http://jpype.readthedocs.io/en/stable/

