from typing import Any, Text


class _JStringProto(Text):
    def __add__(self, other: Text) -> Text: ...

    def __len__(self) -> int: ...

    def __getitem__(self, i: int) -> Text: ...

    def __contains__(self, other: Text) -> bool: ...

    def __hash__(self) -> Any: ...
