#!/usr/bin/env python3
"""Stage the ported test/jpypetest/*.py files into
project/android/testapp/tests/ before running buildozer.

There is no forked copy of the desktop test suite to maintain: the files
under testapp/tests/ (other than __init__.py) are a generated build
artifact - gitignored, regenerated by this script from test/jpypetest/
itself. test/jpypetest/common.py's isAndroid()/skipOnAndroid() (and any
@common.skipOnAndroid(...)-decorated test methods in individual files, see
test_attr.py/test_classloader.py/test_fault.py/test_forname.py/
test_jclass.py/test_jvmfinder.py for examples) are what let the exact same
source files serve both platforms - this script's only job is to get
those unmodified files physically into testapp/tests/, since that's the
one location proven to survive p4a's build (see testapp/tests/__init__.py's
docstring for why a straight `source.dir` pointed at test/jpypetest/
itself isn't used instead: p4a bundles the app as compiled .pyc only, so
whatever directory layout unittest discovery needs has to already be
right there in the app's own source tree, not one level up in a sibling
directory p4a never packages).

Run from anywhere; re-run after editing test/jpypetest/*.py or
testapp/tests/__init__.py's TEST_MODULES list, and before every
`buildozer android debug`.
"""
import shutil
import sys
from os.path import abspath, dirname, join

_ANDROID_DIR = dirname(abspath(__file__))
_REPO_ROOT = join(_ANDROID_DIR, '..', '..')
_SRC_DIR = join(_REPO_ROOT, 'test', 'jpypetest')
_DST_DIR = join(_ANDROID_DIR, 'testapp', 'tests')


def main():
    sys.path.insert(0, join(_ANDROID_DIR, 'testapp'))
    import tests  # testapp/tests/__init__.py - the checked-in TEST_MODULES manifest.

    wanted = {'common.py'} | {name + '.py' for name in tests.TEST_MODULES}

    from os import listdir, remove
    for existing in listdir(_DST_DIR):
        if existing == '__init__.py' or existing in wanted:
            continue
        if existing.endswith('.py'):
            print('sync_tests: removing stale', existing)
            remove(join(_DST_DIR, existing))

    for name in sorted(wanted):
        shutil.copyfile(join(_SRC_DIR, name), join(_DST_DIR, name))
    print('sync_tests: staged {} files into {}'.format(len(wanted), _DST_DIR))


if __name__ == '__main__':
    main()
